```{r}
library(Seurat)
library(SeuratData)
library(patchwork)
library(Signac)

# InstallData("ifnb")
# LoadData("ifnb")
```

```{r}
(\() {
  # res <- readRDS("../sim/dis_1000cells_500genes_1/res.rds")
  cnt <- res$counts_with_batches
  atac_cnt <- res$atacseq_obs
  mt <- res$cell_meta
  rownames(cnt) <- paste0("gene", 1:nrow(cnt))
  rownames(atac_cnt) <- paste0("region", 1:nrow(atac_cnt))
  colnames(cnt) <- colnames(atac_cnt) <- rownames(mt) <- paste0("cell", 1:ncol(cnt), "_type", mt$pop)
  
  so <- CreateSeuratObject(
    cnt,
    project = "IntegTest",
    assay = "RNA",
    names.field = 1,
    names.delim = "_",
    meta.data = mt
  )
  
  so[["ATAC"]] <- CreateAssayObject(counts = atac_cnt)
  
  batches <- SplitObject(so, split.by = "batch")
  
  batches <- lapply(X = batches, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 300)
  })
  
  features <- SelectIntegrationFeatures(object.list = batches)
  
  immune.anchors <- FindIntegrationAnchors(object.list = batches, anchor.features = features)
  immune.combined <- IntegrateData(anchorset = immune.anchors)
  DefaultAssay(immune.combined) <- "integrated"

  # Run the standard workflow for visualization and clustering
  immune.combined <- ScaleData(immune.combined, verbose = FALSE)
  immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
  immune.combined <- RunUMAP(immune.combined, reduction = "pca", dims = 1:30)
  immune.combined <- FindNeighbors(immune.combined, reduction = "pca", dims = 1:30)
  immune.combined <- FindClusters(immune.combined, resolution = 0.5)
  
  p1 <- DimPlot(immune.combined, reduction = "umap", group.by = "batch")
  p2 <- DimPlot(immune.combined, reduction = "umap", group.by = "pop")
  # p2 <- DimPlot(immune.combined, reduction = "umap", label = TRUE, repel = TRUE)
  p1 + p2
})() %>% print()
```

```{r}
seurat_bench_integ <- function(rna, atac, mt, cnt_ref, mt_ref, cnt_q, mt_q) {
  
  so <- CreateSeuratObject(
    rna,
    project = "IntegTest",
    assay = "RNA",
    names.field = 1,
    names.delim = "_",
    meta.data = mt
  )
  
  so[["ATAC"]] <- CreateAssayObject(counts = atac)
  
  so_q <- CreateSeuratObject(
    cnt_q,
    project = "IntegTest",
    assay = "ATAC",
    names.field = 1,
    names.delim = "_",
    meta.data = mt_q
  )
  
  DefaultAssay(so) <- "RNA"
  so <- SCTransform(so, verbose = FALSE) 
  
  # normalize multiome ATAC
  DefaultAssay(so) <- "ATAC"
  so <- RunTFIDF(so)
  so <- FindTopFeatures(so, min.cutoff = "q0")
  
  # normalize query
  so_q<- RunTFIDF(so_q)
  
  so_ref <- CreateSeuratObject(
    cnt_ref,
    project = "IntegTest",
    assay = "RNA",
    names.field = 1,
    names.delim = "_",
    meta.data = mt_ref
  )
  
  so_ref = SCTransform(object = so_ref) %>% RunPCA() %>% RunUMAP(dims = 1:50, return.model = TRUE) 
  
  DefaultAssay(so) <-  "RNA"
  DefaultAssay(so_ref) <- "RNA"
  
  so.ext <- PrepareBridgeReference(reference = so_ref,
                                   bridge = so, 
                                   reference.reduction = "pca",
                                   reference.dims = 1:50,
                                   normalization.method = "LogNormalize"
  )
  
  bridge.anchor <- FindBridgeTransferAnchors(extended.reference = so.ext, 
                                             query = so_q,
                                             reduction = "lsiproject",
                                             dims = 2:50
  )
  
  so_q <- MapQuery(anchorset = bridge.anchor, 
                   reference = so_ref, 
                   query = so_q, 
                   refdata = list(
                     l1 = "pop"),
                   reduction.model = "umap" 
  )
  
  lst(query = so_q, ref = so_ref, ext = so.ext, so = so)
}
```


```{r}
so_q <- (function(){
  # res <- readRDS("../sim/dis_1000cells_500genes_1/res.rds")
  res <- res$res
  cnt <- res$counts_with_batches
  atac_cnt <- res$atacseq_obs
  mt <- res$cell_meta
  rownames(cnt) <- paste0("gene", 1:nrow(cnt))
  rownames(atac_cnt) <- paste0("region", 1:nrow(atac_cnt))
  colnames(cnt) <- colnames(atac_cnt) <- rownames(mt) <- paste0("cell", 1:ncol(cnt), "_type", mt$pop)
  
  b1 <- mt$batch == 1; b2 <- mt$batch == 2; b3 <- mt$batch == 3
  cnt_b1 <- cnt[, b1]; cnt_b2 <- cnt[, b2]; cnt_b3 <- cnt[, b3]
  atac_b1 <- atac_cnt[, b1]; atac_b2 <- atac_cnt[, b2]; atac_b3 <- atac_cnt[, b3]
  mt_b1 <- mt[b1, ]; mt_b2 <- mt[b2, ]; mt_b3 <- mt[b3, ]
  
   seurat_bench_integ(cnt_b1, atac_b1, mt_b1, cnt_b3, mt_b3, atac_b2, mt_b2)
})()

DimPlot(so_q$query, group.by = "predicted.l1", reduction = "ref.umap", label = TRUE) + ggtitle("ATAC") + NoLegend()
DimPlot(so_q$query, group.by = "pop", reduction = "ref.umap", label = TRUE) + ggtitle("ATAC") + NoLegend()
```

```{r}
(\(){
  

ref_cnts <- so_q$ext@reference@assays[["Bridge"]]@data
ref_meta <- so_q$ext@reference@meta.data$pop %>% as.character()
q_cnts <- so_q$query@reductions[["ref.Bridge.reduc"]]@cell.embeddings %>% t()
q_meta <- so_q$query@meta.data$pop %>% as.character() %>% paste0("_q")

# plot_tsne(ref_cnts, ref_meta) %>% print()
# plot_tsne(q_cnts, q_meta) %>% print()
plot_tsne(cbind(ref_cnts, q_cnts), c(ref_meta, q_meta)) %>% print()
})()
```

```{r}
install.packages('devtools')
library(devtools)
install_github('welch-lab/liger')
library(rliger)
library(Seurat)
library(stringr)
```

```{r}
(\(){
  # rna = readRDS("~/scMultiSim/temp/UINMFVignette/SNAREseq_RNA.RDS")
  # shared_atac = readRDS("~/scMultiSim/temp/UINMFVignette/SNAREseq_chromatin_accessibility_shared.RDS")
  # unshared_atac = readRDS("~/scMultiSim/temp/UINMFVignette/SNARE_seq_unshared_chromatin_features.RDS") 
  # browser()
  
  
  D5T1 <- readRDS('~/scMultiSim/temp/liger-scATAC-scRNA/GSM4138888_scATAC_BMMC_D5T1.RDS')
  rna1 <- readRDS('~/scMultiSim/temp/liger-scATAC-scRNA/GSM4138872_scRNA_BMMC_D1T1.rds')
  rna2 <- readRDS('~/scMultiSim/temp/liger-scATAC-scRNA/GSM4138873_scRNA_BMMC_D1T2.rds')
  bmmc.rna <- cbind(rna1,rna2)
  rm(rna1, rna2)
  
  bmmc.data <- list(atac = D5T1, rna = bmmc.rna)
  int.bmmc <- createLiger(bmmc.data)
  rm(D5T1, bmmc.rna, bmmc.data)
  gc()
  
  int.bmmc <- normalize(int.bmmc)
  int.bmmc <- selectGenes(int.bmmc, datasets.use = 2)
  int.bmmc <- scaleNotCenter(int.bmmc)
  
  int.bmmc <- optimizeALS(int.bmmc, k = 20)
  int.bmmc <- quantile_norm(int.bmmc)
  int.bmmc <- louvainCluster(int.bmmc, resolution = 0.2)
  
  int.bmmc <- runUMAP(int.bmmc, distance = 'cosine', n_neighbors = 30, min_dist = 0.3)
  browser()
  plotByDatasetAndCluster(int.bmmc, axis.labels = c('UMAP 1', 'UMAP 2'))
})()
```
