// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rnaSimEdgeCpp
Rcpp::List rnaSimEdgeCpp(NumericMatrix s_base, NumericMatrix kon, NumericMatrix koff, NumericMatrix geff, IntegerVector regulators, NumericVector curr_cif_in, double grn_effect, NumericVector hge_scale, NumericVector scale_s, IntegerVector cell_pop, double intr_noise, NumericVector den_x, NumericVector den_y, IntegerVector cell_idx, NumericVector prev_values_in, int keep_prev_val, bool no_grn);
RcppExport SEXP _scMultiSim_rnaSimEdgeCpp(SEXP s_baseSEXP, SEXP konSEXP, SEXP koffSEXP, SEXP geffSEXP, SEXP regulatorsSEXP, SEXP curr_cif_inSEXP, SEXP grn_effectSEXP, SEXP hge_scaleSEXP, SEXP scale_sSEXP, SEXP cell_popSEXP, SEXP intr_noiseSEXP, SEXP den_xSEXP, SEXP den_ySEXP, SEXP cell_idxSEXP, SEXP prev_values_inSEXP, SEXP keep_prev_valSEXP, SEXP no_grnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type s_base(s_baseSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type kon(konSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type koff(koffSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type geff(geffSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type regulators(regulatorsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type curr_cif_in(curr_cif_inSEXP);
    Rcpp::traits::input_parameter< double >::type grn_effect(grn_effectSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hge_scale(hge_scaleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type scale_s(scale_sSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cell_pop(cell_popSEXP);
    Rcpp::traits::input_parameter< double >::type intr_noise(intr_noiseSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type den_x(den_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type den_y(den_ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cell_idx(cell_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prev_values_in(prev_values_inSEXP);
    Rcpp::traits::input_parameter< int >::type keep_prev_val(keep_prev_valSEXP);
    Rcpp::traits::input_parameter< bool >::type no_grn(no_grnSEXP);
    rcpp_result_gen = Rcpp::wrap(rnaSimEdgeCpp(s_base, kon, koff, geff, regulators, curr_cif_in, grn_effect, hge_scale, scale_s, cell_pop, intr_noise, den_x, den_y, cell_idx, prev_values_in, keep_prev_val, no_grn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scMultiSim_rnaSimEdgeCpp", (DL_FUNC) &_scMultiSim_rnaSimEdgeCpp, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_scMultiSim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
