# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rnaSimEdgeCpp <- function(s_base, kon, koff, geff, regulators, curr_cif_in, grn_effect, hge_scale, scale_s, cell_pop, intr_noise, den_x, den_y, cell_idx, prev_values_in, keep_prev_val, no_grn) {
    .Call(`_scMultiSim_rnaSimEdgeCpp`, s_base, kon, koff, geff, regulators, curr_cif_in, grn_effect, hge_scale, scale_s, cell_pop, intr_noise, den_x, den_y, cell_idx, prev_values_in, keep_prev_val, no_grn)
}

